language: c
cache: apt
env:
  global:
    - enable_coverage=yes
    - PG_PRELOAD=cstore_fdw
  matrix:
    - PGVERSION=9.3
    - PGVERSION=9.4
    - PGVERSION=9.5
    - PGVERSION=40.0
before_install:
  - git clone --depth 1 https://gist.github.com/9963879.git tools
  - tools/setup_apt.sh
  - tools/nuke_pg.sh
install:
  - sudo apt-get install protobuf-c-compiler
  - sudo apt-get install libprotobuf-c0-dev
  - sudo locale-gen da_DK
  - sudo locale-gen da_DK.utf8
  - sudo pip install cpp-coveralls
  - tools/install_pg.sh
  - tools/install_citus.sh
before_script:
  - chmod 777 .
  - chmod 777 data
  - chmod 666 data/*
  - tools/config_and_start_cluster.sh
script: tools/pg_travis_test.sh
after_success:
  - sudo chmod 666 *.gcda
  - coveralls --exclude cstore.pb-c.c --exclude cstore.pb-c.h
